# Generated by Selenium IDE
import time

import pytest
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By


class TestBaidu():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_baidu(self):
    self.driver.get("https://www.baidu.com/")
    self.driver.set_window_size(1382, 754)
    self.driver.find_element(By.ID, "kw").send_keys("awk")
    self.driver.find_element(By.ID, "su").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "Linux awk命令详解 - 小a玖拾柒 - 博客园").click()
    self.vars["win4889"] = self.wait_for_window(2000)
    element = self.driver.find_element(By.LINK_TEXT, "Linux awk命令详解 - 小a玖拾柒 - 博客园")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.vars["root"] = self.driver.current_window_handle
    self.driver.switch_to.window(self.vars["win4889"])
    element = self.driver.find_element(By.CSS_SELECTOR, ".buryit")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.switch_to.window(self.vars["root"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["win4889"])
    self.driver.close()
  
if __name__ == "__main__":  # 命令行：py.test
  pytest.main()